#+TITLE: HAUNT GH PAGE TEMPLATE
#+AUTHOR: me

* status

It works now for blogs and atom feeds only

other builders are not supported or tested up to now

* what for

this repo is my try-out on github pages using guile haunt

* how come

well, I mainly copied and pasted stuff from [[https://github.com/PromyLOPh/guix-install-action][guix-install-action]] and [[https://gist.github.com/MichaelCurrin/a698731096f78240f653faf9a9127cba][how-to-deploy-to-github-pages-with-custom-workflow]]

so thanks for the two authors' work!

without them I would never be able to use haunt on github!

* usage

just fork or clone this repo

then write your posts using common mark in post directory

put the images in the image directory

and you can configure the haunt.scm of course

It now can publish to the projects github page automatically upon push

of course you might need to wait for a while

remember to change the domain and basepath in haunt.scm to suit your need!

* todo

- guile-reader

  get guile-reader to work, so that we can use skribe

  I am afraid that we might need a prebuild executable somehow

  because configuring always complains that no scm_take_u8vector

- better template

  now it is just barebone with a valid github workflow action file

  I wonder if somehow I can add some nice css guide here

  but the problem is, I have 0 interest in frontend!
