name: Build and Deploy 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependency
        run: |
          sudo apt update
          sudo apt install guile-3.0 guile-3.0-dev gperf
          wget http://launchpadlibrarian.net/756818992/guile-commonmark_0.1.2+20240812-3_amd64.deb
          sudo apt install ./guile-commonmark_0.1.2+20240812-3_amd64.deb
          git clone https://git.launchpad.net/ubuntu/+source/guile-reader
          cd guile-reader
          ./configure && make && make install
	  
      - name: Install Haunt
        run: |
          tar -xf /home/runner/Repo/haunt-0.3.0.tar.gz
          cd /home/runner/Repo/haunt-0.3.0
          ./configure
          make
          make install
          cd ~
          rm -rf /home/runner/Repo/haunt-0.3.0/

      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Build
        run: |
          haunt build

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
