name: Build and Deploy 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependency
        run: |
          sudo apt update
          sudo apt install guile-3.0 guile-3.0-dev gperf build-essential autoconf automake make
          wget http://launchpadlibrarian.net/756818992/guile-commonmark_0.1.2+20240812-3_amd64.deb
          sudo apt install ./guile-commonmark_0.1.2+20240812-3_amd64.deb

      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Install Haunt
        run: |
          pwd
          tar -xf guile-reader-0.6.tar.gz
          cd guile-reader-0.6
          ./configure
          make
          make install
          cd ../
          tar -xf haunt-0.3.0.tar.gz
          cd haunt-0.3.0
          ./configure
          make
          make install
          cd ../
          rm -rf haunt-0.3.0/
          rm -rf guile-reader-0.6/	  

      - name: Build
        run: |
          haunt build

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
