name: Build and Deploy 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependency
        run: |
          sudo apt update
	  sudo apt install guile guile-reader guile-commonmark

      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Install haunt
        run: |
          tar -xf haunt-0.3.0.tar.gz
          cd haunt-0.3.0
          ./configure
          make
          make install
	  cd ../

      - name: Build
        run: |
          haunt build

      - name: Clean
        run: |
          rm -rf haunt-0.3.0/

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
